language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

matrix:
 allow_failures:
   - go: master

sudo: required

before_install:
   - sudo apt-get install libffi-dev python-cffi
   - export PATH=$HOME/gopath/bin:$PATH

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
