language: go

go:
  - 1.5.2
  - tip

sudo: false

before_install:
   - export PATH=$HOME/gopath/bin:$PATH

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
